/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.3.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Cell { 'value' : Value, 'name' : string }
export type ConversationId = string;
export interface ConversationSummary {
  'otherParticipant' : Principal,
  'lastMessageAt' : Time,
  'otherUsername' : string,
  'lastMessagePreview' : string,
  'lastMessageFromCaller' : boolean,
  'conversationId' : ConversationId,
  'unreadCount' : bigint,
  'otherDisplayName' : string,
  'otherProfilePictureHash' : [] | [ExternalBlob],
}
export type Error = { 'FrontendOriginsNotConfigured' : null } |
  {
    'MixedSsoSources' : {
      'otherKeys' : Array<string>,
      'ssoKeys' : Array<string>,
    }
  } |
  { 'Stale' : { 'ageNs' : bigint } } |
  { 'MalformedCandid' : null } |
  { 'AmbiguousAttribute' : { 'field' : string, 'sources' : Array<string> } } |
  { 'NoAttributes' : null } |
  { 'UnknownNonce' : null } |
  { 'UntrustedSsoSource' : { 'domain' : string } } |
  { 'MissingField' : string } |
  { 'FrontendOriginMismatch' : { 'got' : string, 'expected' : Array<string> } };
export type ExternalBlob = Uint8Array;
export interface FollowUserResponse {
  'principal' : Principal,
  'username' : string,
  'displayName' : string,
  'profilePictureHash' : [] | [ExternalBlob],
}
export interface Message {
  'id' : bigint,
  'createdAt' : Time,
  'text' : string,
  'recipient' : Principal,
  'sender' : Principal,
  'conversationId' : ConversationId,
}
export type MessagingError = { 'messageTooLong' : { 'maxLength' : bigint } } |
  { 'blocked' : null } |
  { 'recipientNotFound' : null } |
  { 'notMutual' : null } |
  { 'selfMessage' : null } |
  { 'emptyMessage' : null };
export interface MutualFollowStatus {
  'callerFollowsOther' : boolean,
  'otherFollowsCaller' : boolean,
  'isMutual' : boolean,
}
export interface Notification {
  'id' : bigint,
  'notificationType' : NotificationType,
  'createdAt' : Time,
  'isRead' : boolean,
  'actorUsername' : string,
  'actorPrincipal' : Principal,
}
export type NotificationType = { 'repost' : bigint } |
  { 'like' : bigint } |
  { 'quote' : bigint } |
  { 'mention' : bigint } |
  { 'reply' : bigint } |
  { 'follow' : null };
export interface PaginatedFollows {
  'nextOffset' : [] | [bigint],
  'hasMore' : boolean,
  'users' : Array<FollowUserResponse>,
}
export interface PaginatedMessages {
  'hasMore' : boolean,
  'messages' : Array<Message>,
  'nextCursor' : [] | [bigint],
}
export interface PaginatedNotifications {
  'hasMore' : boolean,
  'notifications' : Array<Notification>,
  'nextCursor' : [] | [bigint],
}
export interface PaginatedPosts {
  'hasMore' : boolean,
  'posts' : Array<PostResponse>,
  'nextCursor' : [] | [bigint],
}
export interface PostResponse {
  'id' : bigint,
  'postType' : PostType,
  'authorUsername' : string,
  'likeCount' : bigint,
  'isRepostedByCurrentUser' : boolean,
  'authorProfilePictureHash' : [] | [ExternalBlob],
  'repostCount' : bigint,
  'createdAt' : Time,
  'text' : string,
  'author' : Principal,
  'mediaHash' : [] | [ExternalBlob],
  'replyCount' : bigint,
  'mediaType' : [] | [string],
  'editedAt' : [] | [Time],
  'authorDisplayName' : string,
  'isLikedByCurrentUser' : boolean,
}
export type PostType = { 'repost' : bigint } |
  { 'quote' : bigint } |
  { 'original' : null } |
  { 'reply' : bigint };
export type Result = { 'ok' : Message } |
  { 'err' : MessagingError };
export type Result_1 = { 'ok' : null } |
  { 'err' : Error };
export interface Result__1 { 'hasMore' : boolean, 'rows' : Array<Array<Cell>> }
export type Time = bigint;
export interface TrendingHashtag { 'tag' : string, 'count' : bigint }
export interface UserProfile {
  'bio' : string,
  'username' : string,
  'displayName' : string,
  'createdAt' : Time,
  'updatedAt' : Time,
  'headerImageHash' : [] | [ExternalBlob],
  'profilePictureHash' : [] | [ExternalBlob],
}
export interface UserProfileResponse {
  'bio' : string,
  'isBlockedByCurrentUser' : boolean,
  'principal' : Principal,
  'username' : string,
  'displayName' : string,
  'isMutedByCurrentUser' : boolean,
  'followersCount' : bigint,
  'createdAt' : Time,
  'updatedAt' : Time,
  'headerImageHash' : [] | [ExternalBlob],
  'followingCount' : bigint,
  'isFollowedByCurrentUser' : boolean,
  'profilePictureHash' : [] | [ExternalBlob],
  'postsCount' : bigint,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export type Value = { 'int' : bigint } |
  { 'nat' : bigint } |
  { 'float' : number } |
  { 'bool' : boolean } |
  { 'null' : null } |
  { 'text' : string };
export interface _ImmutableObjectStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _ImmutableObjectStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _ImmutableObjectStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '__accessControlState' : ActorMethod<[], any>,
  '__blocks' : ActorMethod<[], any>,
  '__conversations' : ActorMethod<[], any>,
  '__followers' : ActorMethod<[], any>,
  '__following' : ActorMethod<[], any>,
  '__hashtagIndex' : ActorMethod<[], any>,
  '__messages' : ActorMethod<[], any>,
  '__mutes' : ActorMethod<[], any>,
  '__nextMessageId' : ActorMethod<[], any>,
  '__nextNotificationId' : ActorMethod<[], bigint>,
  '__nextPostId' : ActorMethod<[], bigint>,
  '__postLikes' : ActorMethod<[], any>,
  '__postReplies' : ActorMethod<[], any>,
  '__postReposts' : ActorMethod<[], any>,
  '__posts' : ActorMethod<[], any>,
  '__repostIndex' : ActorMethod<[], any>,
  '__userNotifications' : ActorMethod<[], any>,
  '__userPostCounts' : ActorMethod<[], any>,
  '__userProfiles' : ActorMethod<[], any>,
  '__usernameToUser' : ActorMethod<[], any>,
  '_immutableObjectStorageBlobsAreLive' : ActorMethod<
    [Array<Uint8Array>],
    Array<boolean>
  >,
  '_immutableObjectStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_immutableObjectStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_immutableObjectStorageCreateCertificate' : ActorMethod<
    [string],
    _ImmutableObjectStorageCreateCertificateResult
  >,
  '_immutableObjectStorageRefillCashier' : ActorMethod<
    [[] | [_ImmutableObjectStorageRefillInformation]],
    _ImmutableObjectStorageRefillResult
  >,
  '_immutableObjectStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initialize_access_control' : ActorMethod<[], undefined>,
  '_internet_identity_sign_in_finish' : ActorMethod<[], Result_1>,
  '_internet_identity_sign_in_start' : ActorMethod<[], Uint8Array>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'blockUser' : ActorMethod<[Principal], undefined>,
  'checkUsernameAvailability' : ActorMethod<[string], boolean>,
  'createPost' : ActorMethod<
    [string, [] | [ExternalBlob], [] | [string]],
    PostResponse
  >,
  'createReply' : ActorMethod<
    [bigint, string, [] | [ExternalBlob], [] | [string]],
    PostResponse
  >,
  'deletePost' : ActorMethod<[bigint], undefined>,
  'editPost' : ActorMethod<[bigint, string], PostResponse>,
  'execute' : ActorMethod<[string], Result__1>,
  'followUser' : ActorMethod<[Principal], undefined>,
  /**
   * / Return the backend's public API documentation as Markdown.
   */
  'getApiDoc' : ActorMethod<[], string>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  /**
   * / List the caller's conversations, most recent message first.
   */
  'getConversations' : ActorMethod<[], Array<ConversationSummary>>,
  'getFollowers' : ActorMethod<[string, bigint, bigint], PaginatedFollows>,
  'getFollowing' : ActorMethod<[string, bigint, bigint], PaginatedFollows>,
  'getGlobalFeed' : ActorMethod<[[] | [bigint], bigint], PaginatedPosts>,
  'getHomeFeed' : ActorMethod<[[] | [bigint], bigint], PaginatedPosts>,
  /**
   * / Fetch a page of a conversation's history, newest first. `before` is an
   * / exclusive cursor on message id; `null` starts from the newest message.
   */
  'getMessages' : ActorMethod<
    [ConversationId, [] | [bigint], bigint],
    PaginatedMessages
  >,
  /**
   * / Whether the caller and `other` follow each other, so the frontend can
   * / decide whether to show the Message button.
   */
  'getMutualFollowStatus' : ActorMethod<[Principal], MutualFollowStatus>,
  'getNotifications' : ActorMethod<
    [[] | [bigint], bigint],
    PaginatedNotifications
  >,
  'getPost' : ActorMethod<[bigint], [] | [PostResponse]>,
  'getPostsByHashtag' : ActorMethod<
    [string, [] | [bigint], bigint],
    PaginatedPosts
  >,
  'getPostsByUser' : ActorMethod<
    [Principal, [] | [bigint], bigint],
    PaginatedPosts
  >,
  'getPostsByUsername' : ActorMethod<
    [string, [] | [bigint], bigint],
    PaginatedPosts
  >,
  'getPrincipalByUsername' : ActorMethod<[string], [] | [Principal]>,
  'getProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getProfileByUsername' : ActorMethod<[string], [] | [UserProfileResponse]>,
  'getReplies' : ActorMethod<[bigint, [] | [bigint], bigint], PaginatedPosts>,
  'getTrendingHashtags' : ActorMethod<[bigint], Array<TrendingHashtag>>,
  /**
   * / Total unread messages across all of the caller's conversations.
   */
  'getUnreadMessageCount' : ActorMethod<[], bigint>,
  'getUnreadNotificationCount' : ActorMethod<[], bigint>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfileResponse]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'likePost' : ActorMethod<[bigint], undefined>,
  'markAllNotificationsRead' : ActorMethod<[], undefined>,
  /**
   * / Mark a conversation's messages as read for the caller.
   */
  'markConversationRead' : ActorMethod<[ConversationId], undefined>,
  'markNotificationRead' : ActorMethod<[bigint], undefined>,
  'muteUser' : ActorMethod<[Principal], undefined>,
  'quotePost' : ActorMethod<
    [bigint, string, [] | [ExternalBlob], [] | [string]],
    PostResponse
  >,
  'repostPost' : ActorMethod<[bigint], PostResponse>,
  'schema' : ActorMethod<[], string>,
  'searchPosts' : ActorMethod<[string, [] | [bigint], bigint], PaginatedPosts>,
  'searchUsers' : ActorMethod<[string, bigint], Array<UserProfileResponse>>,
  /**
   * / Send a direct message to `recipient`. Requires a mutual follow and no
   * / block in either direction. Returns the caller-actionable error otherwise.
   */
  'sendMessage' : ActorMethod<[Principal, string], Result>,
  'setProfile' : ActorMethod<[string, string, string], undefined>,
  'unblockUser' : ActorMethod<[Principal], undefined>,
  'undoRepost' : ActorMethod<[bigint], undefined>,
  'unfollowUser' : ActorMethod<[Principal], undefined>,
  'unlikePost' : ActorMethod<[bigint], undefined>,
  'unmuteUser' : ActorMethod<[Principal], undefined>,
  'updateHeaderImage' : ActorMethod<[[] | [ExternalBlob]], undefined>,
  'updateProfilePicture' : ActorMethod<[[] | [ExternalBlob]], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];